[package]
name = "everybodycodes"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
clap = {version = "4.0.29", features = ["derive"]}
paste = "1.0.9"
regex = "1.7.0"
nom = "7.1.3"
hex = "0.4.3"
glam = "0.25.0"
